### ISSUE TITLE
industry menu needs a login

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#655]
https://github.com/poff-bnff/web2021/blob/b881e6cdff1195896a150d4e8f456aa18457b5ab/ssg/source/_templates/header_industry.pug#L54-L62

kommenrteeritud välja on MY CALENDAR osa

### TODO's
- [x] login olgu industry menüüs olemas
- [x] #656

**Comment by mitselek** [comment]
https://github.com/poff-bnff/web2021/blob/b881e6cdff1195896a150d4e8f456aa18457b5ab/ssg/source/_templates/header_industry.pug#L63-L65
//- ul
//-     li#logIn.dropdown_el(style={cursor: 'pointer', display: 'none'})
//-         a(onclick = 'saveUrl()' href=`/${lang_path}login`)= self.label.menu.mainLogin
selle jupi asemele laename toimiva siit
https://github.com/poff-bnff/web2021/blob/b881e6cdff1195896a150d4e8f456aa18457b5ab/ssg/source/_templates/header_poff.pug#L64-L67

**Comment by mitselek** [comment]
TODO's
- [ ] login olgu industry menüüs olemas
- [ ] sisse saab ainult eventivali kaudu

**Comment by mitselek** [comment]
hunt toetab nüüd autentimismeetodi määramist
https://github.com/poff-bnff/oauth/commit/d1fef5adb7711af0204d1a5d23cc67cc1be00484
